### ISSUE TITLE
Error bumping s3ql formula

### ISSUE THREAD

**Issue by chenrui333** [dawidd6/homebrew-update-pypi-resources#2]
When I tried to use this to bump the dependencies for s3ql, running into some page parsing issue, here is the error log:
```
$ brew update-pypi-resources s3ql
Warning: writing updates back to formula
==> apsw
Error: 767: unexpected token at '<!DOCTYPE html>
<html lang="en">
```

apsw resource is in here, https://pypi.org/project/apsw/#files

**Comment by dawidd6** [comment]
Can you run the command again with `--verbose` flag and show the output?

**Comment by chenrui333** [comment]
full log:

<details>
<summary>brew update-pypi-resources --verbose s3ql</summary>

```
$ brew update-pypi-resources --verbose s3ql
Warning: writing updates back to formula
==> apsw
Error: 767: unexpected token at '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="defaultLanguage" content="en">
    <meta name="availableLanguages" content="en, es, fr, ja, pt_BR, uk, el, de, zh_Hans, ru">



    <title>Page Not Found (404) · PyPI</title>
    <meta name="description" content="The Python Package Index (PyPI) is a repository of software for the Python programming language.">

    <link rel="stylesheet" href="/static/css/warehouse.c73e3988.css">
    <link rel="stylesheet" href="/static/css/fontawesome.6002a161.css">
    <link rel="stylesheet" href="/static/css/regular.98fbf39a.css">
    <link rel="stylesheet" href="/static/css/solid.c3b5f0b5.css">
    <link rel="stylesheet" href="/static/css/brands.2c303be1.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic%7CSource+Code+Pro:500">
    <noscript>
      <link rel="stylesheet" href="/static/css/noscript.14e57721.css">
    </noscript>


  <link href="https://fonts.googleapis.com/css?family=Ewert" rel="stylesheet">


    <link rel="icon" href="/static/images/favicon.6a76275d.ico" type="image/x-icon">

    <link rel="alternate" type="application/rss+xml" title="RSS: 40 latest updates" href="/rss/updates.xml">
    <link rel="alternate" type="application/rss+xml" title="RSS: 40 newest packages" href="/rss/packages.xml">


    <meta property="og:url" content="https://pypi.org/pypi/apsw-3.9.2/json/">
    <meta property="og:site_name" content="PyPI">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://pypi.org/static/images/twitter.90915068.jpg">
    <meta property="og:title" content="Page Not Found (404)">
    <meta property="og:description" content="The Python Package Index (PyPI) is a repository of software for the Python programming language.">

    <link rel="search" type="application/opensearchdescription+xml" title="PyPI" href="/opensearch.xml">


    <script
      src="https://cdn.ravenjs.com/3.26.2/raven.min.js"
      integrity="sha384-D6LXy67EIC102DTuqypxwQsTHgiatlbvg7q/1YAWFb6lRyZ1lIZ6bGDsX7jxHNKA"
      crossorigin="anonymous">
    </script>

    <script async
            data-ga-id="UA-55961911-1"
            data-sentry-frontend-dsn="https://3a67b35c9dc248a191d761410b095861@sentry.io/1231155"
            src="/static/js/warehouse.5a36742c.js">
    </script>


    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-55961911-1"></script>
    <script defer src="https://www.fastly-insights.com/insights.js?k=6a52360a-f306-421e-8ed5-7417d0d4a4e9&dnt=true"></script>
  </head>

  <body data-controller="viewport-toggle">

<div class="viewport-section viewport-section--dark">
  <div class="viewport-section__content">
    <a href="/">
      <img alt="PyPI" src="/static/images/logo-small.6eef541e.svg">
    </a>
    <h1 class="viewport-section__heading">We looked everywhere but couldn't find this page</h1>


<form class="search-form search-form--large search-form--fullwidth" action="/search/" role="search">
  <label for="search" class="sr-only">Search PyPI</label>
  <input id="search" class="search-form__search large-input" type="text" name="q" placeholder="Search projects" autocomplete="off" spellcheck="false" autocapitalize="off">
  <button type="submit" class="search-form__button">
    <i class="fa fa-search" aria-hidden="true"></i>
    <span class="sr-only">Search</span>
  </button>
</form>



    <div class="viewport-section__text">
      <p>
        <strong>Error code 404</strong>
        <br>
        <a href="/">Back to the homepage</a>
      </p>
    </div>

  </div>
</div>

  <div class="viewport-section viewport-section--ee">
    <div class="viewport-section__content">
      <h2 class="viewport-section__heading">And now for something <br><span>completely different</span></h2>
      <div class="viewport-section__video">
        <div class="viewport-section__video-container">
          <iframe title="Monty Python - The Cheese Shop Sketch" width="560" height="315" src="https://www.youtube-nocookie.com/embed/zB8pbUW5n1g?rel=0&enablejsapi=1&showinfo=0&iv_load_policy=3&origin=https://pypi.org" frameborder="0" allowfullscreen></iframe>
        </div>
        <p><a href="http://www.montypython.net/scripts/cheese.php" title="External link" target="_blank" rel="noopener">View video transcript</a></p>
      </div>
    </div>
  </div>


  </body>

</html>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Taps/dawidd6/homebrew-update-pypi-resources/cmd/brew-update-pypi-resources.rb:29:in `latest_url_and_checksum'
/usr/local/Homebrew/Library/Taps/dawidd6/homebrew-update-pypi-resources/cmd/brew-update-pypi-resources.rb:68:in `block in <module:Homebrew>'
/usr/local/Homebrew/Library/Taps/dawidd6/homebrew-update-pypi-resources/cmd/brew-update-pypi-resources.rb:57:in `each'
/usr/local/Homebrew/Library/Taps/dawidd6/homebrew-update-pypi-resources/cmd/brew-update-pypi-resources.rb:57:in `<module:Homebrew>'
/usr/local/Homebrew/Library/Taps/dawidd6/homebrew-update-pypi-resources/cmd/brew-update-pypi-resources.rb:14:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```

</details>

**Comment by dawidd6** [comment]
Should be fixed now, thanks for reporting!
